### PR TITLE
Fixes and clean ups

### PR DESCRIPTION
**Pull request by salvy**

### CODE REVIEW

**Comment by salvy** [comment]
Ah I see, but before they were 64bit http://daedalusx64.svn.sourceforge.net/viewvc/daedalusx64/trunk/Source/OSHLE/patch_regs_hle.inl?revision=628&pathrev=628

We changed them to 32bit to get some speed, but as your example if the high bit is set the result will be different, that's why I reverted it back to 64 bit.
The only difference is that before they were unsigned though, I can change them if you want.

**Comment by salvy** [comment]
I tested quiet bit of games, and haven't seen any issues, but yea it would be nice to know why it was removed in the first place  ;)

MRC = Multi Racing Championship

**Comment by hulkholden** [comment]
So in the old version of patch_regs_hle, we were doing this:

gGPR[REG_v0]._u64 = CurrSR & SR_IE;

With this change, it's doing this:

gGPR[REG_v0]._s64 = (s64)(CurrSR & SR_IE);

That's probably the same effect in most places, but I'm just worried that it'll cause some subtle bugs if we're not careful.

(of course, maybe the original code was bugged :)

With the texrect thing we might as well take your fixed version, and I'll try to figure out which rom I was trying to fix by removing the negative check.

**Comment by hulkholden** [comment]
I merged the changes, with a couple of small fixes.

**Comment by salvy** [comment]
Yes, I think we should be good since going back to Daedalus 7, these were 64bit as well.

**Pull request closed without merging**
